dataset:
    name: EXHAMDataset
    root: ./data/EXHAMDataset
    metadata_path: null
    image_extension: null
    batch_size: 32
    val_size: 0.1
    test_size: 0.1

preprocess:
    img_size: 256

model:
    name: CapsuleNetworkWithAttributes32
    channels: 3
    primary_dim: 8
    pose_dim: 7 # output_dim will be pose_dim + 1 (first dim stores logits for predictions)
    num_classes: 2
    routing_steps: 3
    routing_algorithm: sigmoid

trainer:
    name: CapsNetTrainerVAs
    epochs: 70
    learning_rate: 0.001
    lr_decay: 0.96
    loss:
        name: CombinedLoss
        margin_loss_lambda: 0 # Capsule margin loss balance
        margin_loss_gamma: 0 # Focal term, common starting value
        reconstruction_loss_scale: 0.00001 # Lowered to avoid dominating others
        attribute_loss_lambda: 1.0 # Main classification task
        malignancy_loss_lambda: 1.0 # Secondary classificaiton task
        segmentation_loss_lambda: 0 # Often scaled up because segmentation losses tend to be smaller in magnitude
        tc_loss_beta: 0.05 # Total correlation loss usually small to avoid over-regularizing

callbacks:
    - name: PlotCallback
    - name: ReconstructionCallback
      frequency: 7
    - name: EarlyStoppingCallback
      patience: 10
      min_delta: 0.03
      restore_best_weights: True

metrics:
    - type: f1
      per_attribute: True
    - type: precision
      per_attribute: True
    - type: recall
      per_attribute: True

system:
    seed: 123
    augment: True
    save_name: baseline_model_normalized_TC
    save_path: ./checkpoints/
    has_visual_attributes: True
    use_weighted_metrics: False

perturbation:
    num_samples: 2
    is_global: True

evaluate:
    split_size: 0.2
