dataset:
    name: EXHAMDataset
    root: ./data/EXHAMDataset
    metadata_path: null
    image_extension: null
    augment: False
    batch_size: 32
    val_size: 0.05
    test_size: 0.9

preprocess:
    img_size: 256

model:
    name: CapsuleNetworkWithAttributes32
    channels: 3
    primary_dim: 8
    output_dim: 16
    num_classes: 2
    routing_steps: 3
    routing_algorithm: sigmoid

trainer:
    name: CapsNetTrainerVAs
    epochs: 40
    learning_rate: 0.001
    lr_decay: 0.96
    loss:
        name: CombinedLoss
        # reconstruction_loss_scale: 0.0
        attribute_loss_lambda: 10.0

callbacks:
    - name: PlotCallback
    - name: ReconstructionCallback
      frequency: 3
    - name: EarlyStoppingCallback
      patience: 1
      min_delta: 0.03
      restore_best_weights: True

system:
    seed: 123
    save_name: testing_model
    save_path: ./checkpoints/

perturbation:
    num_samples: 2
    is_global: True

evaluate:
    split_size: 0.2
