callbacks:
    - name: PlotCallback
    - frequency: 7
      name: ReconstructionCallback
    - min_delta: 0.03
      name: EarlyStoppingCallback
      patience: 20
      restore_best_weights: true
dataset:
    batch_size: 32
    image_extension: null
    metadata_path: null
    name: EXHAMDataset
    root: ./data/EXHAMDataset
    test_size: 0.1
    val_size: 0.1
evaluate:
    split_size: 0.2
metrics:
    - per_attribute: true
      type: f1
    - per_attribute: true
      type: precision
    - per_attribute: true
      type: recall
model:
    channels: 3
    name: CapsNetWithAttributesMLP
    num_classes: 2
    pose_dim: 16
    primary_dim: 8
    routing_algorithm: sigmoid
    routing_steps: 3
perturbation:
    is_global: true
    num_samples: 2
preprocess:
    img_size: 256
system:
    augment: true
    save_name: experiment_noTCLoss
    save_path: ./checkpoints/
    seed: 123
trainer:
    epochs: 200
    learning_rate: 0.0001
    loss:
        components:
            # AttributeLoss:
            #     lambda: 1.0
            #     params: {}
            MalignancyLoss:
                lambda: 1.0
                params: {}
    lr_decay: 0.96
    name: CapsNetTrainerHungarian
