dataset:
    name: ISICDataset
    root: ./data/ISICDataset
    metadata_path: ./ISIC_2020_Training_GroundTruth_v2.csv
    image_extension: png
    batch_size: 512
    val_size: 0.2
    test_size: 0.2

preprocess:
    img_size: 256

model:
    name: ResnetClassifier
    num_classes: 2 # Binary classification 0: benign, 1: malignant

trainer:
    name: ResnetClassifierTrainer
    epochs: 200
    learning_rate: 0.0001
    lr_decay: 0.95
    loss:
        components:
            MalignancyLoss:
                lambda: 1.0
                params: {}

callbacks:
    - name: PlotCallback
    - name: EarlyStoppingCallback
      patience: 20
      min_delta: 0.01
      restore_best_weights: True

system:
    seed: 123
    augment: True
    save_name: resnet18_baseline
    save_path: ./checkpoints/
    has_visual_attributes: False
    use_weighted_metrics: True

evaluate:
    split_size: 0.2
