dataset:
    name: EXHAMDataset
    root: ./data/EXHAMDataset
    metadata_path: null
    image_extension: null
    batch_size: 24
    val_size: 0.1
    test_size: 0.1

preprocess:
    img_size: 256

model:
    name: CapsNetWithAttributesMLPUpconv
    channels: 3
    primary_dim: 8
    pose_dim: 16
    num_classes: 2
    routing_steps: 3
    routing_algorithm: softmax
    pretrained_encoder_path: checkpoints/new_best_in_town/best_finetune_model.pth
    load_pretrained: True
    freeze_encoder: False

trainer:
    name: CapsNetTrainerMPL
    epochs: 200
    learning_rate: 0.0001
    lr_decay: 0.96
    loss:
        components:
            AttributeLoss:
                lambda: 1.0
                params: {}
            MalignancyLoss:
                lambda: 4.0
                params:
                    focal_gamma: 2.0
                    focal_alpha: 0.25
            MSRPerceptualLoss:
                lambda: 0.2
                params:
                    alpha: 1.0
                    beta: 1.0
                    lambda_bg_global: 1.0
                    lambda_bg_local: 0.1
            # DisentanglementLoss:
            #     lambda: 2000.0
            #     params: {}
            # MaskAlignmentLoss:
            #     lambda: 1.4
            #     params: {}

callbacks:
    - name: PlotCallback
    - name: ReconstructionCallback
      frequency: 5
    - name: EarlyStoppingCallback
      patience: 10
      min_delta: 0.03
      restore_best_weights: True

metrics:
    - type: f1
      per_attribute: True
    - type: precision
      per_attribute: True
    - type: recall
      per_attribute: True

system:
    seed: 123
    augment: True
    save_name: default_with_constrained_routing
    save_path: ./checkpoints/
    has_visual_attributes: True

perturbation:
    num_samples: 2
    is_global: True

evaluate:
    split_size: 0.2
