dataset:
    name: EXHAMDataset
    root: ./data/EXHAMDataset
    metadata_path: null
    image_extension: null
    batch_size: 32
    val_size: 0.1
    test_size: 0.1

preprocess:
    img_size: 256

model:
    name: ModelPretrainedCapsnet
    num_classes: 7
    pose_dim: 7
    pretrained_encoder_path: ./checkpoints/resnet34_baseline.pth.tar
    channels: 3
    primary_dim: 8
    routing_steps: 3
    routing_algorithm: sigmoid

trainer:
    name: CapsNetTrainerVAs
    epochs: 70
    learning_rate: 0.001
    lr_decay: 0.96
    loss:
        name: CombinedLoss
        margin_loss_lambda: 0.5 # Capsule margin loss balance
        margin_loss_gamma: 2.0 # Focal term, common starting value
        reconstruction_loss_scale: 0.0005 # Lowered to avoid dominating others
        attribute_loss_lambda: 10.0 # Main classification task
        malignancy_loss_lambda: 0.5 # Secondary classificaiton task
        segmentation_loss_lambda: 0 # Often scaled up because segmentation losses tend to be smaller in magnitude
        tc_loss_beta: 0.1 # Total correlation loss usually small to avoid over-regularizing

callbacks:
    - name: PlotCallback
      filename: pretrained_acc.png
    - name: EarlyStoppingCallback
      patience: 20
      min_delta: 0.01
      restore_best_weights: True

metrics:
    - type: f1
      per_attribute: True
    - type: precision
      per_attribute: True
    - type: recall
      per_attribute: True

system:
    seed: 123
    augment: True
    save_name: resnet18_pretrained_capsnet
    save_path: ./checkpoints/
    has_visual_attributes: True
    use_weighted_metrics: True

evaluate:
    split_size: 0.2
